"""Change plan: reject look-alike (mixed-script) hostnames, including their punycode form."""
KIND, SCOPE = "feat", "security"

EDITS = [{'file': 'urlshort/validation.py',
  'find': 'import ipaddress\nimport re\nfrom urllib.parse import urlsplit\n',
  'replace': 'import ipaddress\nimport re\nimport unicodedata\nfrom urllib.parse import urlsplit\n'},
 {'file': 'urlshort/validation.py',
  'find': 'def _matches(host: str, domains: frozenset[str]) -> bool:',
  'replace': '# Scripts that legitimately mix inside one name (e.g. Japanese uses kanji with kana) count as one '
             'group.\n'
             '_SCRIPT_GROUPS = {"HIRAGANA": "CJK", "KATAKANA": "CJK", "HANGUL": "CJK"}\n'
             '\n'
             '\n'
             'def _scripts(label: str) -> set[str]:\n'
             '    """Unicode scripts of the letters in a hostname label (digits and hyphens are script-neutral)."""\n'
             '    scripts = set()\n'
             '    for ch in label:\n'
             '        if ch.isalpha():\n'
             '            script = unicodedata.name(ch, "UNKNOWN").split(" ")[0]\n'
             '            scripts.add(_SCRIPT_GROUPS.get(script, script))\n'
             '    return scripts\n'
             '\n'
             '\n'
             'def _is_lookalike(host: str) -> bool:\n'
             '    """True if any label mixes writing systems, e.g. Latin with Cyrillic ("pаypal" with a Cyrillic '
             '"а").\n'
             '\n'
             '    Punycode labels (xn--...) are decoded first, so the encoded form of a look-alike is caught too; a '
             'label\n'
             '    that does not decode is treated as suspicious. Single-script internationalised names stay valid.\n'
             '    """\n'
             '    for label in host.split("."):\n'
             '        if label.startswith("xn--"):\n'
             '            try:\n'
             '                label = label.encode("ascii").decode("idna")\n'
             '            except UnicodeError:\n'
             '                return True\n'
             '        if len(_scripts(label)) > 1:\n'
             '            return True\n'
             '    return False\n'
             '\n'
             '\n'
             'def _matches(host: str, domains: frozenset[str]) -> bool:'},
 {'file': 'urlshort/validation.py',
  'find': '        raise InvalidInput("internal or private hosts are not allowed")\n',
  'replace': '        raise InvalidInput("internal or private hosts are not allowed")\n'
             '    if _is_lookalike(host):\n'
             '        raise InvalidInput("hostname mixes writing systems (possible look-alike of another '
             'domain)")\n'},
 {'file': 'tests/service/test_lookalike.py',
  'create': '"""Look-alike (homoglyph) domains are rejected (AC-LOOKALIKE-*)."""\n'
            'import pytest\n'
            'from fastapi.testclient import TestClient\n'
            '\n'
            'from urlshort.errors import InvalidInput\n'
            'from urlshort.validation import validate_url\n'
            '\n'
            '\n'
            '@pytest.mark.parametrize("url", [\n'
            '    "https://p\\u0430ypal.com/login",            # Latin "paypal" with a Cyrillic "а"\n'
            '    "https://xn--pypal-4ve.com/login",          # the same name in its punycode form\n'
            '    "https://secure.\\u0430pple.com/",           # look-alike in one label of several\n'
            '    "https://xn--zz-.com/",                     # punycode that does not decode\n'
            '])\n'
            'def test_mixed_script_hostnames_are_rejected(client: TestClient, url: str) -> None:\n'
            '    """AC-LOOKALIKE-1"""\n'
            '    resp = client.post("/api/v1/links", json={"url": url})\n'
            '    assert resp.status_code == 400 and "writing systems" in resp.json()["error"]["message"]\n'
            '\n'
            '\n'
            '@pytest.mark.parametrize("url", [\n'
            '    "https://\\u043f\\u0440\\u0438\\u043c\\u0435\\u0440.\\u0440\\u0444/",   # Cyrillic only\n'
            '    "https://\\u4f8b\\u3048.jp/",                       # Japanese kanji + hiragana: one script group\n'
            '    "https://xn--e1afmkfd.xn--p1ai/",                  # the Cyrillic name above, in punycode\n'
            '    "https://caf\\u00e9-7.example/menu",                # Latin with an accent and digits\n'
            '])\n'
            'def test_single_script_internationalised_names_are_accepted(url: str) -> None:\n'
            '    """AC-LOOKALIKE-2"""\n'
            '    assert validate_url(url, max_length=2048).startswith("https://")\n'
            '\n'
            '\n'
            'def test_lookalike_error_is_an_invalid_input() -> None:\n'
            '    with pytest.raises(InvalidInput):\n'
            '        validate_url("https://g\\u043e\\u043egle.com/", max_length=2048)\n'}]
