"""Change plan: per-link max_clicks (brownfield). Generated by scripts in the commit history; the edits are
exact text replacements against the v0.9.0 baseline, applied by the development agent."""
KIND, SCOPE = "feat", "links"

EDITS = [{'file': 'urlshort/storage.py',
  'find': '    click_count INTEGER NOT NULL DEFAULT 0,\n    stats_token_hash TEXT\n);',
  'replace': '    click_count INTEGER NOT NULL DEFAULT 0,\n    stats_token_hash TEXT,\n    max_clicks INTEGER\n);'},
 {'file': 'urlshort/storage.py', 'find': 'SCHEMA_VERSION = 2\n', 'replace': 'SCHEMA_VERSION = 3\n'},
 {'file': 'urlshort/storage.py',
  'find': '        ("clicks", "ip_key_id", "ALTER TABLE clicks ADD COLUMN ip_key_id TEXT")),\n}\n',
  'replace': '        ("clicks", "ip_key_id", "ALTER TABLE clicks ADD COLUMN ip_key_id TEXT")),\n'
             '    3: (("links", "max_clicks", "ALTER TABLE links ADD COLUMN max_clicks INTEGER"),),\n'
             '}\n'},
 {'file': 'urlshort/storage.py',
  'find': 'SET_SCHEMA_VERSION = "PRAGMA user_version = 2"',
  'replace': 'SET_SCHEMA_VERSION = "PRAGMA user_version = 3"'},
 {'file': 'urlshort/storage.py',
  'find': '    stats_token_hash: str | None = None   # sha256 of the per-link stats token; the token itself is never '
          'stored\n',
  'replace': '    stats_token_hash: str | None = None   # sha256 of the per-link stats token; the token itself is '
             'never stored\n'
             '    max_clicks: int | None = None         # human clicks allowed; None means unlimited\n'},
 {'file': 'urlshort/storage.py',
  'find': '                    stats_token_hash=row["stats_token_hash"])',
  'replace': '                    stats_token_hash=row["stats_token_hash"], max_clicks=row["max_clicks"])'},
 {'file': 'urlshort/storage.py',
  'find': '                  link.stats_token_hash)\n',
  'replace': '                  link.stats_token_hash, link.max_clicks)\n'},
 {'file': 'urlshort/storage.py',
  'find': '" stats_token_hash) VALUES (?, ?, ?, ?, ?, ?, ?, ?)"',
  'replace': '" stats_token_hash, max_clicks) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)"'},
 {'file': 'urlshort/storage.py',
  'find': '                " ORDER BY created_at DESC LIMIT 1", (owner, target_url)).fetchone()',
  'replace': '                " AND max_clicks IS NULL ORDER BY created_at DESC LIMIT 1", (owner, '
             'target_url)).fetchone()'},
 {'file': 'urlshort/storage.py',
  'find': '    def record_click(self, click: Click) -> None: ...\n',
  'replace': '    def record_click(self, click: Click) -> None: ...\n'
             '    def record_click_with_limit(self, click: Click) -> bool: ...\n'},
 {'file': 'urlshort/storage.py',
  'find': '    def clicks_for(self, code: str) -> list[Click]:\n        with self._lock:',
  'replace': '    def record_click_with_limit(self, click: Click) -> bool:\n'
             '        """Atomically enforce max_clicks and record the click. Returns False when the cap is reached.\n'
             '\n'
             '        The check and the increment are ONE conditional UPDATE inside BEGIN IMMEDIATE, so concurrent\n'
             '        redirects (threads or processes) can never overshoot the cap. Bots are checked against the cap '
             'but\n'
             '        do not consume it.\n'
             '        """\n'
             '        with self._lock:\n'
             '            self._conn.execute("BEGIN IMMEDIATE")\n'
             '            try:\n'
             '                if click.is_bot:\n'
             '                    allowed = self._conn.execute(\n'
             '                        "SELECT 1 FROM links WHERE code = ? AND (max_clicks IS NULL OR click_count < '
             'max_clicks)",\n'
             '                        (click.code,)).fetchone() is not None\n'
             '                else:\n'
             '                    allowed = self._conn.execute(\n'
             '                        "UPDATE links SET click_count = click_count + 1"\n'
             '                        " WHERE code = ? AND (max_clicks IS NULL OR click_count < max_clicks)",\n'
             '                        (click.code,)).rowcount == 1\n'
             '                if allowed:\n'
             '                    self._conn.execute(\n'
             '                        "INSERT INTO clicks(code, ts, referrer_host, agent_family, is_bot, ip_id, '
             'ip_key_id)"\n'
             '                        " VALUES (?, ?, ?, ?, ?, ?, ?)",\n'
             '                        (click.code, _iso(click.ts), click.referrer_host, click.agent_family, '
             'int(click.is_bot),\n'
             '                         click.ip_id, click.ip_key_id))\n'
             '                self._conn.execute("COMMIT")\n'
             '                return allowed\n'
             '            except Exception:\n'
             '                self._conn.execute("ROLLBACK")\n'
             '                raise\n'
             '\n'
             '    def clicks_for(self, code: str) -> list[Click]:\n'
             '        with self._lock:'},
 {'file': 'urlshort/service.py',
  'find': 'from .errors import AliasConflict, CodeSpaceExhausted, LinkExpired, NotFound',
  'replace': 'from .errors import AliasConflict, CodeSpaceExhausted, LinkExhausted, LinkExpired, NotFound, '
             'StorageUnavailable'},
 {'file': 'urlshort/service.py',
  'find': 'from .validation import validate_alias, validate_ttl, validate_url',
  'replace': 'from .validation import validate_alias, validate_max_clicks, validate_ttl, validate_url'},
 {'file': 'urlshort/service.py',
  'find': '                ttl_seconds: int | None = None) -> CreateResult:',
  'replace': '                ttl_seconds: int | None = None, max_clicks: int | None = None) -> CreateResult:'},
 {'file': 'urlshort/service.py',
  'find': '        ttl = validate_ttl(ttl_seconds, max_ttl=self.settings.max_ttl_seconds)\n'
          '        if alias is None and ttl is None:',
  'replace': '        ttl = validate_ttl(ttl_seconds, max_ttl=self.settings.max_ttl_seconds)\n'
             '        limit = validate_max_clicks(max_clicks)\n'
             '        if alias is None and ttl is None and limit is None:   # only plain permanent links are reused'},
 {'file': 'urlshort/service.py',
  'find': 'self._new_link(validate_alias(alias), target, owner, now, expires, token_hash)',
  'replace': 'self._new_link(validate_alias(alias), target, owner, now, expires, token_hash, limit)'},
 {'file': 'urlshort/service.py',
  'find': 'self._insert_with_generated_code(target, owner, now, expires, token_hash)',
  'replace': 'self._insert_with_generated_code(target, owner, now, expires, token_hash, limit)'},
 {'file': 'urlshort/service.py',
  'find': '                                   "expires_at": expires.isoformat() if expires else None})',
  'replace': '                                   "expires_at": expires.isoformat() if expires else None,\n'
             '                                   "max_clicks": limit})'},
 {'file': 'urlshort/service.py',
  'find': '        try:\n'
          '            self.repo.record_click(click)\n'
          '        except Exception:  # fail open: analytics must never break a redirect (availability > '
          'completeness)\n'
          '            log.exception("click recording failed", extra={"code": code})\n'
          '        return link.target_url',
  'replace': '        if link.max_clicks is not None:\n'
             '            # Capped link: the count IS the business rule, so check-and-count atomically and fail '
             'closed\n'
             '            # (503) if storage is unavailable. Never trust the snapshot read above.\n'
             '            try:\n'
             '                allowed = self.repo.record_click_with_limit(click)\n'
             '            except Exception as exc:\n'
             '                log.exception("click limit check failed", extra={"code": code})\n'
             '                raise StorageUnavailable("could not verify the click limit; please retry") from exc\n'
             '            if not allowed:\n'
             '                raise LinkExhausted(f"link \'{code}\' has reached its click limit")\n'
             '            return link.target_url\n'
             '        try:\n'
             '            self.repo.record_click(click)\n'
             '        except Exception:  # uncapped: fail open, analytics must never break a redirect\n'
             '            log.exception("click recording failed", extra={"code": code})\n'
             '        return link.target_url'},
 {'file': 'urlshort/service.py',
  'find': '    def _new_link(code: str, target: str, owner: str, now: datetime, expires: datetime | None,\n'
          '                  token_hash: str | None) -> Link:\n'
          '        return Link(code=code, target_url=target, owner=owner, created_at=now, expires_at=expires,\n'
          '                    is_active=True, click_count=0, stats_token_hash=token_hash)',
  'replace': '    def _new_link(code: str, target: str, owner: str, now: datetime, expires: datetime | None,\n'
             '                  token_hash: str | None, max_clicks: int | None = None) -> Link:\n'
             '        return Link(code=code, target_url=target, owner=owner, created_at=now, expires_at=expires,\n'
             '                    is_active=True, click_count=0, stats_token_hash=token_hash, '
             'max_clicks=max_clicks)'},
 {'file': 'urlshort/service.py',
  'find': '                                    expires: datetime | None, token_hash: str | None) -> Link:',
  'replace': '                                    expires: datetime | None, token_hash: str | None,\n'
             '                                    max_clicks: int | None = None) -> Link:'},
 {'file': 'urlshort/service.py',
  'find': '            link = self._new_link(code, target, owner, now, expires, token_hash)',
  'replace': '            link = self._new_link(code, target, owner, now, expires, token_hash, max_clicks)'},
 {'file': 'urlshort/errors.py',
  'find': 'class CodeSpaceExhausted(DomainError):\n    code, status = "code_generation_failed", 503\n',
  'replace': 'class CodeSpaceExhausted(DomainError):\n'
             '    code, status = "code_generation_failed", 503\n'
             '\n'
             '\n'
             'class LinkExhausted(DomainError):\n'
             '    code, status = "link_exhausted", 410\n'
             '\n'
             '\n'
             'class StorageUnavailable(DomainError):\n'
             '    code, status = "storage_unavailable", 503\n'},
 {'file': 'urlshort/validation.py',
  'find': '        raise InvalidInput(f"ttl_seconds must be between 1 and {max_ttl}")\n    return ttl_seconds\n',
  'replace': '        raise InvalidInput(f"ttl_seconds must be between 1 and {max_ttl}")\n'
             '    return ttl_seconds\n'
             '\n'
             '\n'
             'MAX_CLICKS_LIMIT = 1_000_000\n'
             '\n'
             '\n'
             'def validate_max_clicks(max_clicks: int | None) -> int | None:\n'
             '    """None means unlimited; otherwise between 1 and MAX_CLICKS_LIMIT human clicks."""\n'
             '    if max_clicks is None:\n'
             '        return None\n'
             '    if max_clicks < 1 or max_clicks > MAX_CLICKS_LIMIT:\n'
             '        raise InvalidInput(f"max_clicks must be between 1 and {MAX_CLICKS_LIMIT}")\n'
             '    return max_clicks\n'},
 {'file': 'urlshort/models.py',
  'find': '    ttl_seconds: int | None = Field(None, ge=1, examples=[86400])\n',
  'replace': '    ttl_seconds: int | None = Field(None, ge=1, examples=[86400])\n'
             '    max_clicks: int | None = Field(None, ge=1, le=1_000_000, examples=[100])\n'},
 {'file': 'urlshort/models.py',
  'find': '    click_count: int\n',
  'replace': '    click_count: int\n    max_clicks: int | None = None\n'},
 {'file': 'urlshort/web/context.py',
  'find': 'is_active=link.is_active, click_count=link.click_count)',
  'replace': 'is_active=link.is_active, click_count=link.click_count,\n'
             '                            max_clicks=link.max_clicks)'},
 {'file': 'urlshort/web/routes_links.py',
  'find': '        result = service.shorten(body.url, owner=owner, alias=body.custom_alias, '
          'ttl_seconds=body.ttl_seconds)',
  'replace': '        result = service.shorten(body.url, owner=owner, alias=body.custom_alias, '
             'ttl_seconds=body.ttl_seconds,\n'
             '                                 max_clicks=body.max_clicks)'},
 {'file': 'tests/service/test_max_clicks.py',
  'create': '"""Per-link click caps (AC-MAXCLICKS-*): atomic enforcement, bots, fail-closed storage, schema v3."""\n'
            'import sqlite3\n'
            'from concurrent.futures import ThreadPoolExecutor\n'
            'from pathlib import Path\n'
            'from threading import Barrier\n'
            '\n'
            'import pytest\n'
            'from fastapi.testclient import TestClient\n'
            '\n'
            'from urlshort.config import Settings\n'
            'from urlshort.errors import InvalidInput, LinkExhausted, StorageUnavailable\n'
            'from urlshort.service import ShortenerService\n'
            'from urlshort.storage import SCHEMA_VERSION, Click, SqliteRepository\n'
            'from urlshort.validation import validate_max_clicks\n'
            '\n'
            'from .helpers import FakeClock\n'
            '\n'
            'CHROME = {"user-agent": "Mozilla/5.0 Chrome/126.0"}\n'
            'BOT = {"user-agent": "Googlebot/2.1"}\n'
            '\n'
            '\n'
            'def test_cap_is_enforced_with_link_exhausted(client: TestClient) -> None:\n'
            '    """AC-MAXCLICKS-1"""\n'
            '    link = client.post("/api/v1/links", json={"url": "https://example.com/offer", "max_clicks": '
            '2}).json()\n'
            '    assert link["max_clicks"] == 2\n'
            '    for _ in range(2):\n'
            '        assert client.get(f"/{link[\'code\']}", headers=CHROME, follow_redirects=False).status_code == '
            '307\n'
            '    refused = client.get(f"/{link[\'code\']}", headers=CHROME, follow_redirects=False)\n'
            '    assert refused.status_code == 410 and refused.json()["error"]["code"] == "link_exhausted"\n'
            '    assert client.get(f"/api/v1/links/{link[\'code\']}").json()["click_count"] == 2\n'
            '\n'
            '\n'
            'def test_cap_holds_under_concurrency(repo: SqliteRepository, clock: FakeClock) -> None:\n'
            '    """AC-MAXCLICKS-1: 40 simultaneous redirects on a 10-click link -> exactly 10 succeed."""\n'
            '    svc = ShortenerService(repo, Settings(), clock=clock)\n'
            '    code = svc.shorten("https://example.com/race", owner="o", max_clicks=10).link.code\n'
            '    barrier = Barrier(40)\n'
            '\n'
            '    def hit(_: int) -> bool:\n'
            '        barrier.wait()\n'
            '        try:\n'
            '            svc.resolve(code, user_agent="Mozilla/5.0 Chrome/126.0")\n'
            '            return True\n'
            '        except LinkExhausted:\n'
            '            return False\n'
            '    with ThreadPoolExecutor(max_workers=40) as pool:\n'
            '        assert sum(pool.map(hit, range(40))) == 10\n'
            '    link = repo.get_link(code)\n'
            '    assert link is not None and link.click_count == 10\n'
            '\n'
            '\n'
            '@pytest.mark.parametrize("value", [0, -1, 1_000_001])\n'
            'def test_out_of_range_caps_are_rejected(client: TestClient, value: int) -> None:\n'
            '    """AC-MAXCLICKS-2"""\n'
            '    resp = client.post("/api/v1/links", json={"url": "https://example.com", "max_clicks": value})\n'
            '    assert resp.status_code == 400 and resp.json()["error"]["code"] == "invalid_input"\n'
            '\n'
            '\n'
            'def test_service_validates_caps_too() -> None:\n'
            '    """AC-MAXCLICKS-2: the rule lives in the service, not only in the HTTP model."""\n'
            '    assert validate_max_clicks(None) is None and validate_max_clicks(5) == 5\n'
            '    with pytest.raises(InvalidInput, match="between 1 and 1000000"):\n'
            '        validate_max_clicks(0)\n'
            '\n'
            '\n'
            'def test_bots_do_not_consume_the_cap(client: TestClient) -> None:\n'
            '    """AC-MAXCLICKS-3"""\n'
            '    code = client.post("/api/v1/links", json={"url": "https://example.com/cap", "max_clicks": '
            '1}).json()["code"]\n'
            '    for _ in range(3):\n'
            '        assert client.get(f"/{code}", headers=BOT, follow_redirects=False).status_code == 307\n'
            '    assert client.get(f"/{code}", headers=CHROME, follow_redirects=False).status_code == 307\n'
            '    assert client.get(f"/{code}", headers=BOT, follow_redirects=False).status_code == 410\n'
            '\n'
            '\n'
            'def test_capped_links_fail_closed_when_storage_breaks(repo: SqliteRepository, clock: FakeClock) -> '
            'None:\n'
            '    svc = ShortenerService(repo, Settings(), clock=clock)\n'
            '    code = svc.shorten("https://example.com/c", owner="o", max_clicks=5).link.code\n'
            '\n'
            '    def broken(click: Click) -> bool:\n'
            '        raise sqlite3.OperationalError("database is locked")\n'
            '    repo.record_click_with_limit = broken  # type: ignore[method-assign]\n'
            '    with pytest.raises(StorageUnavailable):\n'
            '        svc.resolve(code)\n'
            '\n'
            '\n'
            'def test_failed_capped_write_rolls_back_atomically(repo: SqliteRepository, clock: FakeClock) -> None:\n'
            '    svc = ShortenerService(repo, Settings(), clock=clock)\n'
            '    code = svc.shorten("https://example.com/r", owner="o", max_clicks=5).link.code\n'
            '    repo._conn.execute("DROP TABLE clicks")\n'
            '    with pytest.raises(StorageUnavailable):\n'
            '        svc.resolve(code)\n'
            '    link = repo.get_link(code)\n'
            '    assert link is not None and link.click_count == 0\n'
            '\n'
            '\n'
            'def test_capped_links_are_never_reused_for_plain_requests(repo: SqliteRepository, clock: FakeClock) -> '
            'None:\n'
            '    svc = ShortenerService(repo, Settings(), clock=clock)\n'
            '    capped = svc.shorten("https://example.com/same", owner="o", max_clicks=3)\n'
            '    plain = svc.shorten("https://example.com/same", owner="o")\n'
            '    again = svc.shorten("https://example.com/same", owner="o", max_clicks=3)\n'
            '    assert plain.created and plain.link.code != capped.link.code and plain.link.max_clicks is None\n'
            '    assert again.created and again.link.code not in (capped.link.code, plain.link.code)\n'
            '    assert svc.shorten("https://example.com/same", owner="o").link.code == plain.link.code\n'
            '\n'
            '\n'
            'def test_uncapped_links_still_fail_open(repo: SqliteRepository, clock: FakeClock) -> None:\n'
            '    svc = ShortenerService(repo, Settings(), clock=clock)\n'
            '    code = svc.shorten("https://example.com/u", owner="o").link.code\n'
            '    repo._conn.execute("DROP TABLE clicks")\n'
            '    assert svc.resolve(code) == "https://example.com/u"\n'
            '\n'
            '\n'
            'def test_version_2_database_is_upgraded_to_version_3(tmp_path: Path) -> None:\n'
            '    path = tmp_path / "v2.db"\n'
            '    conn = sqlite3.connect(path)\n'
            '    conn.executescript("""\n'
            '        CREATE TABLE links (code TEXT PRIMARY KEY, target_url TEXT NOT NULL, owner TEXT NOT NULL,\n'
            '            created_at TEXT NOT NULL, expires_at TEXT, is_active INTEGER NOT NULL DEFAULT 1,\n'
            '            click_count INTEGER NOT NULL DEFAULT 0, stats_token_hash TEXT);\n'
            "        INSERT INTO links VALUES ('old0001', 'https://example.com', 'o', '2026-01-01T00:00:00+00:00', "
            'NULL, 1, 4, NULL);\n'
            '        PRAGMA user_version = 2;\n'
            '    """)\n'
            '    conn.close()\n'
            '    r = SqliteRepository(str(path))\n'
            '    old = r.get_link("old0001")\n'
            '    assert old is not None and old.click_count == 4 and old.max_clicks is None\n'
            '    assert r._conn.execute("PRAGMA user_version").fetchone()[0] == SCHEMA_VERSION == 3\n'
            '    r.close()\n'}]

# Recorded flawed first drafts, replayed so the gates can be shown catching them.
DEFECTS = {'sqlfmt': [{'file': 'urlshort/storage.py',
             'find': '                    allowed = self._conn.execute(\n'
                     '                        "UPDATE links SET click_count = click_count + 1"\n'
                     '                        " WHERE code = ? AND (max_clicks IS NULL OR click_count < '
                     'max_clicks)",\n'
                     '                        (click.code,)).rowcount == 1',
             'replace': '                    allowed = self._conn.execute(\n'
                        '                        f"UPDATE links SET click_count = click_count + 1 WHERE code = '
                        '\'{click.code}\'"\n'
                        '                        " AND (max_clicks IS NULL OR click_count < max_clicks)").rowcount '
                        '== 1'}],
 'swallow': [{'file': 'urlshort/service.py',
              'find': '            try:\n'
                      '                allowed = self.repo.record_click_with_limit(click)\n'
                      '            except Exception as exc:\n'
                      '                log.exception("click limit check failed", extra={"code": code})\n'
                      '                raise StorageUnavailable("could not verify the click limit; please retry") '
                      'from exc',
              'replace': '            allowed = True\n'
                         '            try:\n'
                         '                allowed = self.repo.record_click_with_limit(click)\n'
                         '            except Exception:\n'
                         '                pass'}]}
